#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);
MODULE_INFO(name, KBUILD_MODNAME);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

#ifdef RETPOLINE
MODULE_INFO(retpoline, "Y");
#endif

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x367398b6, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xb077e70a, __VMLINUX_SYMBOL_STR(clk_unprepare) },
	{ 0x3ce4ca6f, __VMLINUX_SYMBOL_STR(disable_irq) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0xafd762a6, __VMLINUX_SYMBOL_STR(drm_gem_prime_export) },
	{ 0xce102fc0, __VMLINUX_SYMBOL_STR(rpi_firmware_transaction) },
	{ 0xde41cd83, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0x7f9f07e3, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0xa305bb58, __VMLINUX_SYMBOL_STR(__pm_runtime_idle) },
	{ 0x6306d909, __VMLINUX_SYMBOL_STR(drm_dev_register) },
	{ 0xac9c7145, __VMLINUX_SYMBOL_STR(dma_release_from_dev_coherent) },
	{ 0xc3a6c1f1, __VMLINUX_SYMBOL_STR(platform_unregister_drivers) },
	{ 0xf246c744, __VMLINUX_SYMBOL_STR(trace_handle_return) },
	{ 0x815588a6, __VMLINUX_SYMBOL_STR(clk_enable) },
	{ 0xddf196bc, __VMLINUX_SYMBOL_STR(of_find_i2c_adapter_by_node) },
	{ 0x8b70d323, __VMLINUX_SYMBOL_STR(drm_get_edid) },
	{ 0x2d1f095b, __VMLINUX_SYMBOL_STR(drm_atomic_helper_update_plane) },
	{ 0xd8472478, __VMLINUX_SYMBOL_STR(drm_atomic_helper_crtc_duplicate_state) },
	{ 0xa9059416, __VMLINUX_SYMBOL_STR(__pm_runtime_disable) },
	{ 0xc8a9978c, __VMLINUX_SYMBOL_STR(drm_calc_vbltimestamp_from_scanoutpos) },
	{ 0xf9ded91c, __VMLINUX_SYMBOL_STR(drm_dev_alloc) },
	{ 0x923f4dc5, __VMLINUX_SYMBOL_STR(component_unbind_all) },
	{ 0x7aa1756e, __VMLINUX_SYMBOL_STR(kvfree) },
	{ 0x8ea69e7, __VMLINUX_SYMBOL_STR(mipi_dsi_packet_format_is_long) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x5c2e3421, __VMLINUX_SYMBOL_STR(del_timer) },
	{ 0x9f7e36b5, __VMLINUX_SYMBOL_STR(drm_edid_to_eld) },
	{ 0xa0e7e68b, __VMLINUX_SYMBOL_STR(__pm_runtime_use_autosuspend) },
	{ 0xd2af138b, __VMLINUX_SYMBOL_STR(reservation_ww_class) },
	{ 0xe123f3d9, __VMLINUX_SYMBOL_STR(dma_fence_release) },
	{ 0x6e01fd2a, __VMLINUX_SYMBOL_STR(drm_gem_cma_create) },
	{ 0x8de13715, __VMLINUX_SYMBOL_STR(drm_format_vert_chroma_subsampling) },
	{ 0x32c7e039, __VMLINUX_SYMBOL_STR(clk_fixed_factor_ops) },
	{ 0xbfad6df, __VMLINUX_SYMBOL_STR(drm_atomic_helper_wait_for_dependencies) },
	{ 0x3314bb3a, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0xb75735dc, __VMLINUX_SYMBOL_STR(component_add) },
	{ 0x65cfeb2e, __VMLINUX_SYMBOL_STR(__pm_runtime_suspend) },
	{ 0xfd2dbcd8, __VMLINUX_SYMBOL_STR(of_parse_phandle) },
	{ 0xe8005a5a, __VMLINUX_SYMBOL_STR(drm_atomic_set_fence_for_plane) },
	{ 0x1199b01e, __VMLINUX_SYMBOL_STR(drm_mode_config_reset) },
	{ 0xad73041f, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0x7c7221a8, __VMLINUX_SYMBOL_STR(drm_crtc_from_index) },
	{ 0x45f57cd1, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_reset) },
	{ 0x4401a1cc, __VMLINUX_SYMBOL_STR(drm_atomic_helper_wait_for_fences) },
	{ 0xcabe9d78, __VMLINUX_SYMBOL_STR(drm_atomic_helper_commit_hw_done) },
	{ 0x8f0cb089, __VMLINUX_SYMBOL_STR(arm_dma_ops) },
	{ 0xc0ebd0a8, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_mmap) },
	{ 0xa52ecfd9, __VMLINUX_SYMBOL_STR(drm_atomic_helper_page_flip) },
	{ 0x208939a5, __VMLINUX_SYMBOL_STR(devm_snd_dmaengine_pcm_register) },
	{ 0x675809a9, __VMLINUX_SYMBOL_STR(drm_bridge_attach) },
	{ 0xd4c14632, __VMLINUX_SYMBOL_STR(system_unbound_wq) },
	{ 0x5cc509a4, __VMLINUX_SYMBOL_STR(nsecs_to_jiffies) },
	{ 0x741a9baf, __VMLINUX_SYMBOL_STR(drm_atomic_helper_swap_state) },
	{ 0xb6e6d99d, __VMLINUX_SYMBOL_STR(clk_disable) },
	{ 0xacbfb3a4, __VMLINUX_SYMBOL_STR(drm_cvt_mode) },
	{ 0xee89fc46, __VMLINUX_SYMBOL_STR(drm_hdmi_avi_infoframe_quant_range) },
	{ 0x42b754ae, __VMLINUX_SYMBOL_STR(drm_crtc_handle_vblank) },
	{ 0x3ee15874, __VMLINUX_SYMBOL_STR(gpio_to_desc) },
	{ 0xeccd322b, __VMLINUX_SYMBOL_STR(drm_default_rgb_quant_range) },
	{ 0x1afae5e7, __VMLINUX_SYMBOL_STR(down_interruptible) },
	{ 0xd4abfbee, __VMLINUX_SYMBOL_STR(drm_helper_probe_single_connector_modes) },
	{ 0x45b4c1f6, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x4e47a36a, __VMLINUX_SYMBOL_STR(mipi_dsi_host_unregister) },
	{ 0xe41887f3, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_off) },
	{ 0x4205ad24, __VMLINUX_SYMBOL_STR(cancel_work_sync) },
	{ 0x7adeb8d4, __VMLINUX_SYMBOL_STR(ktime_get) },
	{ 0x686c7697, __VMLINUX_SYMBOL_STR(platform_bus_type) },
	{ 0x90f3dc1e, __VMLINUX_SYMBOL_STR(component_bind_all) },
	{ 0xe2fae716, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0xba950764, __VMLINUX_SYMBOL_STR(drm_fbdev_cma_init) },
	{ 0x7dd937b5, __VMLINUX_SYMBOL_STR(devm_ioremap_resource) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x3f1451d, __VMLINUX_SYMBOL_STR(hdmi_infoframe_pack) },
	{ 0x914265c9, __VMLINUX_SYMBOL_STR(drm_of_find_panel_or_bridge) },
	{ 0x42526343, __VMLINUX_SYMBOL_STR(refcount_dec_not_one) },
	{ 0x5ee52022, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x28cc25db, __VMLINUX_SYMBOL_STR(arm_copy_from_user) },
	{ 0xe4ca3b4f, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xc8b9e4b5, __VMLINUX_SYMBOL_STR(component_match_add_release) },
	{ 0xb5c7247e, __VMLINUX_SYMBOL_STR(__pm_runtime_resume) },
	{ 0x63150e06, __VMLINUX_SYMBOL_STR(clk_get_parent) },
	{ 0x27e4824d, __VMLINUX_SYMBOL_STR(trace_event_buffer_reserve) },
	{ 0x98618b77, __VMLINUX_SYMBOL_STR(drm_dev_unref) },
	{ 0xcca98b33, __VMLINUX_SYMBOL_STR(drm_vblank_init) },
	{ 0xc2b6e973, __VMLINUX_SYMBOL_STR(component_master_del) },
	{ 0xca45efbc, __VMLINUX_SYMBOL_STR(drm_format_horz_chroma_subsampling) },
	{ 0x795a3dfe, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0xf7b09a15, __VMLINUX_SYMBOL_STR(drm_connector_list_iter_next) },
	{ 0x1cdb6ceb, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_get_sg_table) },
	{ 0x556e4390, __VMLINUX_SYMBOL_STR(clk_get_rate) },
	{ 0x4d6f705, __VMLINUX_SYMBOL_STR(__drm_atomic_helper_crtc_destroy_state) },
	{ 0xd5835d7b, __VMLINUX_SYMBOL_STR(snd_pcm_hw_constraint_eld) },
	{ 0xcc9bddf, __VMLINUX_SYMBOL_STR(drm_atomic_helper_crtc_reset) },
	{ 0xda5f023b, __VMLINUX_SYMBOL_STR(drm_universal_plane_init) },
	{ 0x93b71cf6, __VMLINUX_SYMBOL_STR(__platform_driver_register) },
	{ 0x526c3a6c, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x6c5ec758, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0xf4fa543b, __VMLINUX_SYMBOL_STR(arm_copy_to_user) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0xfcbff27c, __VMLINUX_SYMBOL_STR(__drm_atomic_helper_plane_duplicate_state) },
	{ 0x1d3a3ead, __VMLINUX_SYMBOL_STR(reservation_object_add_shared_fence) },
	{ 0x5d88742d, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_duplicate_state) },
	{ 0x55334af1, __VMLINUX_SYMBOL_STR(__drm_atomic_helper_crtc_duplicate_state) },
	{ 0xe3d361cf, __VMLINUX_SYMBOL_STR(dma_alloc_from_dev_coherent) },
	{ 0x93de854a, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x2d52d2ae, __VMLINUX_SYMBOL_STR(drm_atomic_helper_set_config) },
	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
	{ 0x990c77b4, __VMLINUX_SYMBOL_STR(drm_panel_bridge_add) },
	{ 0x88ab6fe3, __VMLINUX_SYMBOL_STR(kgdb_active) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0xa14d464f, __VMLINUX_SYMBOL_STR(trace_define_field) },
	{ 0x56072d6b, __VMLINUX_SYMBOL_STR(drm_mm_init) },
	{ 0x127ff854, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0x3dfcdb0f, __VMLINUX_SYMBOL_STR(drm_irq_install) },
	{ 0x429be6d3, __VMLINUX_SYMBOL_STR(remove_conflicting_framebuffers) },
	{ 0xfae026cd, __VMLINUX_SYMBOL_STR(drm_dev_unregister) },
	{ 0xcc337fd5, __VMLINUX_SYMBOL_STR(drm_fbdev_cma_restore_mode) },
	{ 0xfd00388b, __VMLINUX_SYMBOL_STR(drm_atomic_helper_commit_cleanup_done) },
	{ 0xe49a8c4e, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x51d559d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x4fa062d5, __VMLINUX_SYMBOL_STR(dma_fence_init) },
	{ 0xb475bfd2, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_put) },
	{ 0x2aee63f4, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x563766ba, __VMLINUX_SYMBOL_STR(drm_object_attach_property) },
	{ 0x85146123, __VMLINUX_SYMBOL_STR(drm_atomic_helper_prepare_planes) },
	{ 0x9ab12ea0, __VMLINUX_SYMBOL_STR(drm_mode_duplicate) },
	{ 0x6177160c, __VMLINUX_SYMBOL_STR(drm_mode_create_tv_properties) },
	{ 0x4380dcf0, __VMLINUX_SYMBOL_STR(drm_crtc_init_with_planes) },
	{ 0xff771bd, __VMLINUX_SYMBOL_STR(__cpu_online_mask) },
	{ 0x268110c9, __VMLINUX_SYMBOL_STR(drm_atomic_helper_plane_reset) },
	{ 0x1e7ea559, __VMLINUX_SYMBOL_STR(drm_gem_fb_create) },
	{ 0xdac8e0c9, __VMLINUX_SYMBOL_STR(of_find_property) },
	{ 0x3961b196, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0xec869105, __VMLINUX_SYMBOL_STR(snd_dmaengine_pcm_prepare_slave_config) },
	{ 0xaaa96e3a, __VMLINUX_SYMBOL_STR(drm_gem_object_put_unlocked) },
	{ 0x36ce3f90, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_on) },
	{ 0xa2b57bd6, __VMLINUX_SYMBOL_STR(dma_sync_wait) },
	{ 0x8d3bde78, __VMLINUX_SYMBOL_STR(drm_fb_cma_get_gem_obj) },
	{ 0x506fa18b, __VMLINUX_SYMBOL_STR(trace_event_reg) },
	{ 0xb2c912af, __VMLINUX_SYMBOL_STR(drm_fbdev_cma_hotplug_event) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xfd16e532, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x3404417, __VMLINUX_SYMBOL_STR(drm_probe_ddc) },
	{ 0xcd1e7546, __VMLINUX_SYMBOL_STR(dma_fence_free) },
	{ 0x5da089e8, __VMLINUX_SYMBOL_STR(platform_get_resource) },
	{ 0x119f7144, __VMLINUX_SYMBOL_STR(drm_read) },
	{ 0xfb4323e1, __VMLINUX_SYMBOL_STR(dma_fence_signal) },
	{ 0xf8231b08, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0xa38caae0, __VMLINUX_SYMBOL_STR(mod_timer) },
	{ 0xb2f3b8de, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0x52e74f9d, __VMLINUX_SYMBOL_STR(dma_request_chan_by_mask) },
	{ 0x5479134d, __VMLINUX_SYMBOL_STR(snd_soc_unregister_card) },
	{ 0x8e865d3c, __VMLINUX_SYMBOL_STR(arm_delay_ops) },
	{ 0x237f1ded, __VMLINUX_SYMBOL_STR(of_clk_add_hw_provider) },
	{ 0x3c9684fe, __VMLINUX_SYMBOL_STR(dma_fence_context_alloc) },
	{ 0x7f1cd5c5, __VMLINUX_SYMBOL_STR(bus_find_device) },
	{ 0x3a46e84e, __VMLINUX_SYMBOL_STR(of_clk_hw_onecell_get) },
	{ 0x12da7344, __VMLINUX_SYMBOL_STR(drm_atomic_set_fb_for_plane) },
	{ 0x41482d8b, __VMLINUX_SYMBOL_STR(strndup_user) },
	{ 0xf4e97b1a, __VMLINUX_SYMBOL_STR(rpi_firmware_property) },
	{ 0x99ea22c8, __VMLINUX_SYMBOL_STR(drm_debugfs_create_files) },
	{ 0x6f7fa8dc, __VMLINUX_SYMBOL_STR(perf_trace_run_bpf_submit) },
	{ 0xaaecf75d, __VMLINUX_SYMBOL_STR(perf_trace_buf_alloc) },
	{ 0x7c24d500, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0xed440a4b, __VMLINUX_SYMBOL_STR(of_match_device) },
	{ 0x2196324, __VMLINUX_SYMBOL_STR(__aeabi_idiv) },
	{ 0xd73781d7, __VMLINUX_SYMBOL_STR(drm_gem_vm_open) },
	{ 0xf292a7e6, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0x59e5070d, __VMLINUX_SYMBOL_STR(__do_div64) },
	{ 0xbb4b7e7c, __VMLINUX_SYMBOL_STR(drm_gem_vm_close) },
	{ 0x88288e85, __VMLINUX_SYMBOL_STR(kvmalloc_node) },
	{ 0x178d17f9, __VMLINUX_SYMBOL_STR(drm_gem_prime_fd_to_handle) },
	{ 0x904326e4, __VMLINUX_SYMBOL_STR(of_get_address) },
	{ 0x9493055b, __VMLINUX_SYMBOL_STR(drm_plane_helper_disable) },
	{ 0xaaec7e1f, __VMLINUX_SYMBOL_STR(gpiod_get_raw_value_cansleep) },
	{ 0x4969d922, __VMLINUX_SYMBOL_STR(drm_plane_cleanup) },
	{ 0xf3207539, __VMLINUX_SYMBOL_STR(drm_printk) },
	{ 0x3f0d430b, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0x1dfdc844, __VMLINUX_SYMBOL_STR(drm_gem_prime_import) },
	{ 0xc1e39ade, __VMLINUX_SYMBOL_STR(drm_gem_mmap) },
	{ 0x47a49947, __VMLINUX_SYMBOL_STR(drm_atomic_helper_plane_duplicate_state) },
	{ 0x2b6cc8d0, __VMLINUX_SYMBOL_STR(drm_atomic_helper_wait_for_vblanks) },
	{ 0x7ea08ef0, __VMLINUX_SYMBOL_STR(drm_connector_list_iter_end) },
	{ 0x7da62109, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_destroy_state) },
	{ 0x7b466684, __VMLINUX_SYMBOL_STR(__drm_atomic_helper_plane_destroy_state) },
	{ 0x27abf0bf, __VMLINUX_SYMBOL_STR(pm_runtime_enable) },
	{ 0x856a60f4, __VMLINUX_SYMBOL_STR(trace_event_ignore_this_pid) },
	{ 0x986dc1, __VMLINUX_SYMBOL_STR(drm_atomic_helper_check) },
	{ 0x7696ffd9, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0x7d5354ee, __VMLINUX_SYMBOL_STR(dma_fence_default_wait) },
	{ 0x21e3d82d, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_vunmap) },
	{ 0x8ddd8aad, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0xdca9066b, __VMLINUX_SYMBOL_STR(drm_irq_uninstall) },
	{ 0x38a4f7ae, __VMLINUX_SYMBOL_STR(drm_format_num_planes) },
	{ 0x7c9a7371, __VMLINUX_SYMBOL_STR(clk_prepare) },
	{ 0xc73d6202, __VMLINUX_SYMBOL_STR(devm_snd_soc_register_component) },
	{ 0x9367cb46, __VMLINUX_SYMBOL_STR(__platform_register_drivers) },
	{ 0xe867cc36, __VMLINUX_SYMBOL_STR(__pm_runtime_set_status) },
	{ 0xee0fe31b, __VMLINUX_SYMBOL_STR(drm_atomic_helper_commit_modeset_disables) },
	{ 0xfa65616f, __VMLINUX_SYMBOL_STR(drm_crtc_send_vblank_event) },
	{ 0x50fad434, __VMLINUX_SYMBOL_STR(round_jiffies_up) },
	{ 0xb2038652, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0xe4a92e70, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_get) },
	{ 0x2ccf0318, __VMLINUX_SYMBOL_STR(of_get_named_gpio_flags) },
	{ 0xbdf6ea20, __VMLINUX_SYMBOL_STR(trace_event_buffer_commit) },
	{ 0xb315691b, __VMLINUX_SYMBOL_STR(drm_gem_handle_delete) },
	{ 0x7f24de73, __VMLINUX_SYMBOL_STR(jiffies_to_usecs) },
	{ 0xf96639f8, __VMLINUX_SYMBOL_STR(drm_mode_object_put) },
	{ 0x9aae3c7a, __VMLINUX_SYMBOL_STR(devm_clk_get) },
	{ 0x7a9f42fb, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x1a770ac3, __VMLINUX_SYMBOL_STR(drm_detect_hdmi_monitor) },
	{ 0x1a84b0e0, __VMLINUX_SYMBOL_STR(drm_atomic_helper_setup_commit) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x55e4fd80, __VMLINUX_SYMBOL_STR(reservation_object_add_excl_fence) },
	{ 0x598542b2, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0xc268292, __VMLINUX_SYMBOL_STR(snd_soc_unregister_codec) },
	{ 0x63c9ed50, __VMLINUX_SYMBOL_STR(drm_gem_prime_handle_to_fd) },
	{ 0x1c4f56be, __VMLINUX_SYMBOL_STR(rpi_firmware_get) },
	{ 0x76d9b876, __VMLINUX_SYMBOL_STR(clk_set_rate) },
	{ 0xe6bcccf3, __VMLINUX_SYMBOL_STR(drm_panel_bridge_remove) },
	{ 0xd154378d, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_import_sg_table) },
	{ 0x4215a929, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x85531d12, __VMLINUX_SYMBOL_STR(event_triggers_call) },
	{ 0x7e843fb7, __VMLINUX_SYMBOL_STR(drm_connector_unregister) },
	{ 0x6f0d015d, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0x37c26acf, __VMLINUX_SYMBOL_STR(drm_connector_list_iter_begin) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x3fe471d3, __VMLINUX_SYMBOL_STR(devm_clk_hw_register) },
	{ 0xbaa349e1, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0xc9e0a8a1, __VMLINUX_SYMBOL_STR(drm_atomic_helper_commit_planes) },
	{ 0xb9cad492, __VMLINUX_SYMBOL_STR(__drm_atomic_state_free) },
	{ 0xfcec0987, __VMLINUX_SYMBOL_STR(enable_irq) },
	{ 0x8de5cf32, __VMLINUX_SYMBOL_STR(drm_atomic_helper_crtc_destroy_state) },
	{ 0x8beb5c68, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xa33b5cd7, __VMLINUX_SYMBOL_STR(drm_hdmi_avi_infoframe_from_display_mode) },
	{ 0x46d2ac49, __VMLINUX_SYMBOL_STR(unmap_mapping_range) },
	{ 0x4f2fcbab, __VMLINUX_SYMBOL_STR(component_del) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x4702d955, __VMLINUX_SYMBOL_STR(drm_mode_object_get) },
	{ 0xd27f2af0, __VMLINUX_SYMBOL_STR(trace_event_raw_init) },
	{ 0x6f5696fb, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0xdcf48307, __VMLINUX_SYMBOL_STR(ww_mutex_unlock) },
	{ 0x4be7fb63, __VMLINUX_SYMBOL_STR(up) },
	{ 0x5e5dc0df, __VMLINUX_SYMBOL_STR(drm_mode_equal) },
	{ 0xb79ec15d, __VMLINUX_SYMBOL_STR(mipi_dsi_create_packet) },
	{ 0x2ab2a010, __VMLINUX_SYMBOL_STR(drm_mm_insert_node_in_range) },
	{ 0x467b5e14, __VMLINUX_SYMBOL_STR(drm_atomic_helper_cleanup_planes) },
	{ 0x74c134b9, __VMLINUX_SYMBOL_STR(__sw_hweight32) },
	{ 0xf5c2d34d, __VMLINUX_SYMBOL_STR(hdmi_audio_infoframe_init) },
	{ 0xf80e987, __VMLINUX_SYMBOL_STR(drm_mm_takedown) },
	{ 0x98dfb43, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0xb86d6479, __VMLINUX_SYMBOL_STR(radix_tree_lookup) },
	{ 0x62a4e95b, __VMLINUX_SYMBOL_STR(dma_common_mmap) },
	{ 0xc548c21f, __VMLINUX_SYMBOL_STR(pm_runtime_set_autosuspend_delay) },
	{ 0x795b774c, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0xbbef463a, __VMLINUX_SYMBOL_STR(drm_atomic_helper_disable_plane) },
	{ 0x37a40715, __VMLINUX_SYMBOL_STR(trace_raw_output_prep) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0xd7e0a7d9, __VMLINUX_SYMBOL_STR(drm_mode_probed_add) },
	{ 0xeccebb80, __VMLINUX_SYMBOL_STR(component_master_add_with_match) },
	{ 0xb2d48a2e, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xb0a0da0c, __VMLINUX_SYMBOL_STR(rational_best_approximation) },
	{ 0x689e06e, __VMLINUX_SYMBOL_STR(complete) },
	{ 0x1148b623, __VMLINUX_SYMBOL_STR(drm_fbdev_cma_fini) },
	{ 0xf147dcb2, __VMLINUX_SYMBOL_STR(hdmi_spd_infoframe_init) },
	{ 0xe86b10b0, __VMLINUX_SYMBOL_STR(platform_get_irq) },
	{ 0x3c93ea25, __VMLINUX_SYMBOL_STR(trace_seq_printf) },
	{ 0x727c3956, __VMLINUX_SYMBOL_STR(of_drm_find_panel) },
	{ 0x898d67f8, __VMLINUX_SYMBOL_STR(platform_driver_unregister) },
	{ 0xad183055, __VMLINUX_SYMBOL_STR(reservation_object_reserve_shared) },
	{ 0xefa8e2bb, __VMLINUX_SYMBOL_STR(drm_mm_remove_node) },
	{ 0x1c505bdb, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_init) },
	{ 0x46d65d8b, __VMLINUX_SYMBOL_STR(drm_gem_cma_free_object) },
	{ 0x439b82d7, __VMLINUX_SYMBOL_STR(snd_soc_register_codec) },
	{ 0x877d7727, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_vmap) },
	{ 0xf08621fd, __VMLINUX_SYMBOL_STR(of_node_put) },
	{ 0x84a203c6, __VMLINUX_SYMBOL_STR(devm_kmalloc) },
	{ 0x29dec96f, __VMLINUX_SYMBOL_STR(wait_for_completion_timeout) },
	{ 0xb60a7cbc, __VMLINUX_SYMBOL_STR(snd_soc_register_card) },
	{ 0xe8ac9581, __VMLINUX_SYMBOL_STR(devm_request_threaded_irq) },
	{ 0x9aa05c65, __VMLINUX_SYMBOL_STR(drm_atomic_helper_commit_modeset_enables) },
	{ 0x25352d39, __VMLINUX_SYMBOL_STR(drm_mode_crtc_set_gamma_size) },
	{ 0x9bddf7c2, __VMLINUX_SYMBOL_STR(mipi_dsi_host_register) },
	{ 0x9b4210a2, __VMLINUX_SYMBOL_STR(ww_mutex_lock_interruptible) },
	{ 0xd5c720b, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0xc569d8ce, __VMLINUX_SYMBOL_STR(__clk_get_name) },
	{ 0x5acadaa9, __VMLINUX_SYMBOL_STR(dma_fence_signal_locked) },
	{ 0xe3d44117, __VMLINUX_SYMBOL_STR(of_drm_find_bridge) },
	{ 0xb859f38b, __VMLINUX_SYMBOL_STR(krealloc) },
	{ 0x2e7a4300, __VMLINUX_SYMBOL_STR(drm_rgb_quant_range_selectable) },
	{ 0xe5b1a382, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0xfde13f70, __VMLINUX_SYMBOL_STR(drm_atomic_helper_plane_destroy_state) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,drm_kms_helper,snd-soc-core,snd-pcm";

MODULE_ALIAS("of:N*T*Cbrcm,bcm2835-vc4");
MODULE_ALIAS("of:N*T*Cbrcm,bcm2835-vc4C*");
MODULE_ALIAS("of:N*T*Cbrcm,cygnus-vc4");
MODULE_ALIAS("of:N*T*Cbrcm,cygnus-vc4C*");

MODULE_INFO(srcversion, "823A1AB2E834C9545A344EC");
