#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);
MODULE_INFO(name, KBUILD_MODNAME);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

#ifdef RETPOLINE
MODULE_INFO(retpoline, "Y");
#endif

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x367398b6, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xde41cd83, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0x96fdec95, __VMLINUX_SYMBOL_STR(drm_prime_gem_destroy) },
	{ 0xbbb29fbe, __VMLINUX_SYMBOL_STR(drm_fb_helper_set_par) },
	{ 0x6b78bd96, __VMLINUX_SYMBOL_STR(drm_fb_helper_ioctl) },
	{ 0x7f9f07e3, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xcf39918f, __VMLINUX_SYMBOL_STR(drm_crtc_helper_set_config) },
	{ 0x6306d909, __VMLINUX_SYMBOL_STR(drm_dev_register) },
	{ 0x61c856be, __VMLINUX_SYMBOL_STR(drm_gem_put_pages) },
	{ 0xf9ded91c, __VMLINUX_SYMBOL_STR(drm_dev_alloc) },
	{ 0xa9d156b, __VMLINUX_SYMBOL_STR(drm_fb_helper_initial_config) },
	{ 0x7aa1756e, __VMLINUX_SYMBOL_STR(kvfree) },
	{ 0x426b950b, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0xa62ad7e2, __VMLINUX_SYMBOL_STR(drm_gem_object_put) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x656bc048, __VMLINUX_SYMBOL_STR(drm_gem_dmabuf_release) },
	{ 0x3314bb3a, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0x8f0cb089, __VMLINUX_SYMBOL_STR(arm_dma_ops) },
	{ 0x4df8c3b1, __VMLINUX_SYMBOL_STR(drm_fb_helper_unlink_fbi) },
	{ 0xa0457aab, __VMLINUX_SYMBOL_STR(dma_buf_detach) },
	{ 0xfa1f45a3, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_leave) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0xd4abfbee, __VMLINUX_SYMBOL_STR(drm_helper_probe_single_connector_modes) },
	{ 0xe2fae716, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0xd5152710, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0x1bd8ca50, __VMLINUX_SYMBOL_STR(drm_gem_free_mmap_offset) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x5ee52022, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0xe4ca3b4f, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x98618b77, __VMLINUX_SYMBOL_STR(drm_dev_unref) },
	{ 0xcca98b33, __VMLINUX_SYMBOL_STR(drm_vblank_init) },
	{ 0x795a3dfe, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0xf76b0a59, __VMLINUX_SYMBOL_STR(read_current_timer) },
	{ 0x6c5ec758, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0x3bd730c4, __VMLINUX_SYMBOL_STR(drm_fb_helper_unregister_fbi) },
	{ 0xe029ffb5, __VMLINUX_SYMBOL_STR(dma_buf_vunmap) },
	{ 0x884c76b0, __VMLINUX_SYMBOL_STR(usb_get_descriptor) },
	{ 0xf8c621ab, __VMLINUX_SYMBOL_STR(drm_fb_helper_pan_display) },
	{ 0xf4882d83, __VMLINUX_SYMBOL_STR(drm_helper_connector_dpms) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x127ff854, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0x3744cf36, __VMLINUX_SYMBOL_STR(vmalloc_to_pfn) },
	{ 0x51d559d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xe6857cde, __VMLINUX_SYMBOL_STR(drm_prime_pages_to_sg) },
	{ 0x7f873ed8, __VMLINUX_SYMBOL_STR(usb_deregister) },
	{ 0xe87eeec1, __VMLINUX_SYMBOL_STR(drm_helper_mode_fill_fb_struct) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x3961b196, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0x30f14bd0, __VMLINUX_SYMBOL_STR(vmap) },
	{ 0xaaa96e3a, __VMLINUX_SYMBOL_STR(drm_gem_object_put_unlocked) },
	{ 0xedea57d3, __VMLINUX_SYMBOL_STR(dma_buf_put) },
	{ 0xa7a3e0ec, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_var) },
	{ 0xfacd2e14, __VMLINUX_SYMBOL_STR(pgprot_user) },
	{ 0x62fd3ede, __VMLINUX_SYMBOL_STR(usb_control_msg) },
	{ 0xfd16e532, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x99e315f7, __VMLINUX_SYMBOL_STR(drm_gem_object_release) },
	{ 0xf473ffaf, __VMLINUX_SYMBOL_STR(down) },
	{ 0x119f7144, __VMLINUX_SYMBOL_STR(drm_read) },
	{ 0xf8231b08, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0xb2f3b8de, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0xa6bd6cf0, __VMLINUX_SYMBOL_STR(dma_buf_unmap_attachment) },
	{ 0x60e556df, __VMLINUX_SYMBOL_STR(usb_free_coherent) },
	{ 0x7c24d500, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0x362b6f60, __VMLINUX_SYMBOL_STR(drm_dev_unplug) },
	{ 0xde8705d5, __VMLINUX_SYMBOL_STR(drm_fb_helper_prepare) },
	{ 0xd73781d7, __VMLINUX_SYMBOL_STR(drm_gem_vm_open) },
	{ 0xf292a7e6, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0x221097a8, __VMLINUX_SYMBOL_STR(vm_insert_page) },
	{ 0xbb4b7e7c, __VMLINUX_SYMBOL_STR(drm_gem_vm_close) },
	{ 0xcdd158d, __VMLINUX_SYMBOL_STR(sg_alloc_table) },
	{ 0x88288e85, __VMLINUX_SYMBOL_STR(kvmalloc_node) },
	{ 0x178d17f9, __VMLINUX_SYMBOL_STR(drm_gem_prime_fd_to_handle) },
	{ 0x131f21bd, __VMLINUX_SYMBOL_STR(dma_buf_begin_cpu_access) },
	{ 0xf3207539, __VMLINUX_SYMBOL_STR(drm_printk) },
	{ 0x3f0d430b, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0x12f9774c, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_imageblit) },
	{ 0x3f653b74, __VMLINUX_SYMBOL_STR(usb_submit_urb) },
	{ 0xc1e39ade, __VMLINUX_SYMBOL_STR(drm_gem_mmap) },
	{ 0x999520ac, __VMLINUX_SYMBOL_STR(dma_buf_map_attachment) },
	{ 0xe11a5406, __VMLINUX_SYMBOL_STR(drm_gem_dmabuf_export) },
	{ 0xb17a5d7e, __VMLINUX_SYMBOL_STR(drm_framebuffer_unregister_private) },
	{ 0x7696ffd9, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0x89d7c97f, __VMLINUX_SYMBOL_STR(drm_fb_helper_check_var) },
	{ 0x689dc7e3, __VMLINUX_SYMBOL_STR(drm_fb_helper_blank) },
	{ 0xfa65616f, __VMLINUX_SYMBOL_STR(drm_crtc_send_vblank_event) },
	{ 0xb2038652, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0x7a9f42fb, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x79ec08df, __VMLINUX_SYMBOL_STR(drm_fb_helper_alloc_fbi) },
	{ 0x86f29a35, __VMLINUX_SYMBOL_STR(drm_crtc_init) },
	{ 0x598542b2, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x117c8f3e, __VMLINUX_SYMBOL_STR(dma_buf_attach) },
	{ 0x63c9ed50, __VMLINUX_SYMBOL_STR(drm_gem_prime_handle_to_fd) },
	{ 0x511e3ac3, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0x7e843fb7, __VMLINUX_SYMBOL_STR(drm_connector_unregister) },
	{ 0xcf35e62, __VMLINUX_SYMBOL_STR(drm_gem_object_init) },
	{ 0x6f0d015d, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0x41e33cca, __VMLINUX_SYMBOL_STR(fb_deferred_io_cleanup) },
	{ 0x95a2b927, __VMLINUX_SYMBOL_STR(fb_deferred_io_init) },
	{ 0x2ee7fd19, __VMLINUX_SYMBOL_STR(drm_gem_create_mmap_offset) },
	{ 0xbaa349e1, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0x8beb5c68, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x94961283, __VMLINUX_SYMBOL_STR(vunmap) },
	{ 0x78ed4fa3, __VMLINUX_SYMBOL_STR(remap_pfn_range) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xa9a51125, __VMLINUX_SYMBOL_STR(drm_fb_helper_deferred_io) },
	{ 0x4be7fb63, __VMLINUX_SYMBOL_STR(up) },
	{ 0xebdc0b9a, __VMLINUX_SYMBOL_STR(usb_register_driver) },
	{ 0x1db7dc40, __VMLINUX_SYMBOL_STR(pgprot_kernel) },
	{ 0x8de9aaaf, __VMLINUX_SYMBOL_STR(drm_fb_helper_fini) },
	{ 0x4a28d9ce, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all) },
	{ 0x9cd60539, __VMLINUX_SYMBOL_STR(sg_free_table) },
	{ 0x3e884f4b, __VMLINUX_SYMBOL_STR(vm_get_page_prot) },
	{ 0xae981995, __VMLINUX_SYMBOL_STR(drm_prime_sg_to_page_addr_arrays) },
	{ 0x7b141898, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_fillrect) },
	{ 0x1f010653, __VMLINUX_SYMBOL_STR(drm_modeset_unlock_all) },
	{ 0x6def835f, __VMLINUX_SYMBOL_STR(drm_helper_disable_unused_functions) },
	{ 0x42828a9b, __VMLINUX_SYMBOL_STR(dma_buf_end_cpu_access) },
	{ 0x3b1ff16c, __VMLINUX_SYMBOL_STR(drm_fb_helper_setcmap) },
	{ 0xcee6191d, __VMLINUX_SYMBOL_STR(usb_alloc_coherent) },
	{ 0x52c07df, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0x484ee0ae, __VMLINUX_SYMBOL_STR(dma_buf_vmap) },
	{ 0x73e0f7d8, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_copyarea) },
	{ 0x7ac13ae4, __VMLINUX_SYMBOL_STR(drm_gem_get_pages) },
	{ 0x635da34, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_fix) },
	{ 0xde809ed, __VMLINUX_SYMBOL_STR(drm_connector_register) },
	{ 0x3ac1fef9, __VMLINUX_SYMBOL_STR(drm_mode_legacy_fb_format) },
	{ 0xc2dfa496, __VMLINUX_SYMBOL_STR(usb_free_urb) },
	{ 0x837d0f0a, __VMLINUX_SYMBOL_STR(down_timeout) },
	{ 0x6806a58c, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_disable) },
	{ 0xbabec74e, __VMLINUX_SYMBOL_STR(drm_mode_object_find) },
	{ 0x974dc349, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_enter) },
	{ 0xd5c720b, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0xbe89d001, __VMLINUX_SYMBOL_STR(drm_fb_helper_init) },
	{ 0xcfb5909, __VMLINUX_SYMBOL_STR(drm_fb_helper_single_add_all_connectors) },
	{ 0x9174a2a3, __VMLINUX_SYMBOL_STR(usb_alloc_urb) },
	{ 0xe5b1a382, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0xa4097127, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,drm_kms_helper";

MODULE_ALIAS("usb:v17E9p*d*dc*dsc*dp*icFFisc00ip00in*");

MODULE_INFO(srcversion, "687EB26AFF7338D8234FF3E");
