#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);
MODULE_INFO(name, KBUILD_MODNAME);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

#ifdef RETPOLINE
MODULE_INFO(retpoline, "Y");
#endif

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x367398b6, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xfbbb7196, __VMLINUX_SYMBOL_STR(drm_mode_get_hv_timing) },
	{ 0x92b57248, __VMLINUX_SYMBOL_STR(flush_work) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x2689dbe0, __VMLINUX_SYMBOL_STR(drm_edid_get_monitor_name) },
	{ 0x31d43db2, __VMLINUX_SYMBOL_STR(drm_atomic_get_connector_state) },
	{ 0xed7e5b08, __VMLINUX_SYMBOL_STR(drm_bridge_mode_valid) },
	{ 0x7f9f07e3, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0xfd60df2, __VMLINUX_SYMBOL_STR(drm_get_connector_status_name) },
	{ 0x4b5f9e05, __VMLINUX_SYMBOL_STR(drm_calc_timestamping_constants) },
	{ 0x8b70d323, __VMLINUX_SYMBOL_STR(drm_get_edid) },
	{ 0x91fec1cc, __VMLINUX_SYMBOL_STR(drm_rect_calc_vscale) },
	{ 0x6b805816, __VMLINUX_SYMBOL_STR(try_wait_for_completion) },
	{ 0x349cba85, __VMLINUX_SYMBOL_STR(strchr) },
	{ 0x2e8f7975, __VMLINUX_SYMBOL_STR(drm_atomic_nonblocking_commit) },
	{ 0x426b950b, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0xb1b3750b, __VMLINUX_SYMBOL_STR(drm_mode_validate_ycbcr420) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x254da488, __VMLINUX_SYMBOL_STR(drm_bridge_disable) },
	{ 0x9f7e36b5, __VMLINUX_SYMBOL_STR(drm_edid_to_eld) },
	{ 0x13c812, __VMLINUX_SYMBOL_STR(drm_mode_create_from_cmdline_mode) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0xe123f3d9, __VMLINUX_SYMBOL_STR(dma_fence_release) },
	{ 0x228a3dac, __VMLINUX_SYMBOL_STR(framebuffer_release) },
	{ 0x6e01fd2a, __VMLINUX_SYMBOL_STR(drm_gem_cma_create) },
	{ 0xd35f75a1, __VMLINUX_SYMBOL_STR(match_string) },
	{ 0x774d5cff, __VMLINUX_SYMBOL_STR(drm_modeset_drop_locks) },
	{ 0xe8005a5a, __VMLINUX_SYMBOL_STR(drm_atomic_set_fence_for_plane) },
	{ 0x69aa5d30, __VMLINUX_SYMBOL_STR(drm_bridge_pre_enable) },
	{ 0xfa5c6446, __VMLINUX_SYMBOL_STR(unlink_framebuffer) },
	{ 0xa459d25e, __VMLINUX_SYMBOL_STR(drm_property_create_blob) },
	{ 0x1199b01e, __VMLINUX_SYMBOL_STR(drm_mode_config_reset) },
	{ 0xeeaf6f31, __VMLINUX_SYMBOL_STR(drm_atomic_state_clear) },
	{ 0xfe90c4a6, __VMLINUX_SYMBOL_STR(_find_first_zero_bit_le) },
	{ 0x8f0cb089, __VMLINUX_SYMBOL_STR(arm_dma_ops) },
	{ 0x675809a9, __VMLINUX_SYMBOL_STR(drm_bridge_attach) },
	{ 0x6ea40b8, __VMLINUX_SYMBOL_STR(drm_mode_destroy) },
	{ 0x1bf3e000, __VMLINUX_SYMBOL_STR(drm_property_blob_put) },
	{ 0xd4c14632, __VMLINUX_SYMBOL_STR(system_unbound_wq) },
	{ 0xacc51031, __VMLINUX_SYMBOL_STR(seq_puts) },
	{ 0x237c3510, __VMLINUX_SYMBOL_STR(drm_property_blob_get) },
	{ 0x4d974b9c, __VMLINUX_SYMBOL_STR(register_sysrq_key) },
	{ 0xbe33b724, __VMLINUX_SYMBOL_STR(i2c_transfer) },
	{ 0x267fdd4d, __VMLINUX_SYMBOL_STR(drm_atomic_get_plane_state) },
	{ 0xf2fb86ac, __VMLINUX_SYMBOL_STR(fb_sys_read) },
	{ 0xf1421d13, __VMLINUX_SYMBOL_STR(drm_mode_sort) },
	{ 0x8aa0841a, __VMLINUX_SYMBOL_STR(drm_modeset_backoff) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x45b4c1f6, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x4205ad24, __VMLINUX_SYMBOL_STR(cancel_work_sync) },
	{ 0xe2fae716, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0x987c11c7, __VMLINUX_SYMBOL_STR(__pv_phys_pfn_offset) },
	{ 0xe93e49c3, __VMLINUX_SYMBOL_STR(devres_free) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x2b69efe2, __VMLINUX_SYMBOL_STR(cfb_fillrect) },
	{ 0xfd2f67b4, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x5ee52022, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0xfd792e2a, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0x9709dbc5, __VMLINUX_SYMBOL_STR(current_work) },
	{ 0xe4ca3b4f, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0x5fd3bd69, __VMLINUX_SYMBOL_STR(drm_plane_force_disable) },
	{ 0xd3d2483a, __VMLINUX_SYMBOL_STR(platform_device_register_full) },
	{ 0x795a3dfe, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0xc2a15d64, __VMLINUX_SYMBOL_STR(drm_modeset_acquire_fini) },
	{ 0xd472dbff, __VMLINUX_SYMBOL_STR(drm_object_property_set_value) },
	{ 0xf7b09a15, __VMLINUX_SYMBOL_STR(drm_connector_list_iter_next) },
	{ 0xdc562267, __VMLINUX_SYMBOL_STR(sys_copyarea) },
	{ 0x75a73ff6, __VMLINUX_SYMBOL_STR(drm_mode_validate_basic) },
	{ 0x37e74642, __VMLINUX_SYMBOL_STR(get_jiffies_64) },
	{ 0xd697e69a, __VMLINUX_SYMBOL_STR(trace_hardirqs_on) },
	{ 0x9ee9fd56, __VMLINUX_SYMBOL_STR(devres_alloc_node) },
	{ 0xffc6c87a, __VMLINUX_SYMBOL_STR(drm_detect_monitor_audio) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0xda5f023b, __VMLINUX_SYMBOL_STR(drm_universal_plane_init) },
	{ 0x8ea8b153, __VMLINUX_SYMBOL_STR(drm_get_format_info) },
	{ 0x6c5ec758, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0x450f524f, __VMLINUX_SYMBOL_STR(drm_atomic_set_mode_prop_for_crtc) },
	{ 0x5c50a61e, __VMLINUX_SYMBOL_STR(i2c_add_adapter) },
	{ 0x7f23a6b3, __VMLINUX_SYMBOL_STR(mutex_trylock) },
	{ 0x131db64a, __VMLINUX_SYMBOL_STR(system_long_wq) },
	{ 0x7e66cbd6, __VMLINUX_SYMBOL_STR(param_ops_string) },
	{ 0xae277372, __VMLINUX_SYMBOL_STR(__drm_crtc_commit_free) },
	{ 0x40c96041, __VMLINUX_SYMBOL_STR(drm_atomic_set_mode_for_crtc) },
	{ 0x6faf31bf, __VMLINUX_SYMBOL_STR(complete_all) },
	{ 0xbf24f797, __VMLINUX_SYMBOL_STR(fb_set_suspend) },
	{ 0xc631580a, __VMLINUX_SYMBOL_STR(console_unlock) },
	{ 0x93de854a, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xcb2340b8, __VMLINUX_SYMBOL_STR(drm_rect_debug_print) },
	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
	{ 0x59ef50f0, __VMLINUX_SYMBOL_STR(drm_edid_block_valid) },
	{ 0xdd0a2ba2, __VMLINUX_SYMBOL_STR(strlcat) },
	{ 0x88ab6fe3, __VMLINUX_SYMBOL_STR(kgdb_active) },
	{ 0xd3f04e85, __VMLINUX_SYMBOL_STR(drm_bridge_post_disable) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x127ff854, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0xb4611947, __VMLINUX_SYMBOL_STR(drm_atomic_state_alloc) },
	{ 0x3838adc7, __VMLINUX_SYMBOL_STR(fb_deferred_io_mmap) },
	{ 0xdb032670, __VMLINUX_SYMBOL_STR(drm_mode_copy) },
	{ 0xec4224e, __VMLINUX_SYMBOL_STR(drm_atomic_commit) },
	{ 0x44869ff6, __VMLINUX_SYMBOL_STR(drm_mode_find_dmt) },
	{ 0xc6f83bb5, __VMLINUX_SYMBOL_STR(cfb_imageblit) },
	{ 0xe49a8c4e, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x51d559d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xb475bfd2, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_put) },
	{ 0x37d6e4e4, __VMLINUX_SYMBOL_STR(drm_bridge_enable) },
	{ 0x2aee63f4, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x9ab12ea0, __VMLINUX_SYMBOL_STR(drm_mode_duplicate) },
	{ 0x7a890c8, __VMLINUX_SYMBOL_STR(fb_alloc_cmap) },
	{ 0x4380dcf0, __VMLINUX_SYMBOL_STR(drm_crtc_init_with_planes) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x6e30ba8e, __VMLINUX_SYMBOL_STR(drm_rect_rotate_inv) },
	{ 0x99bcfec1, __VMLINUX_SYMBOL_STR(drm_atomic_set_crtc_for_connector) },
	{ 0x3961b196, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0xaaa96e3a, __VMLINUX_SYMBOL_STR(drm_gem_object_put_unlocked) },
	{ 0x40100300, __VMLINUX_SYMBOL_STR(wait_for_completion_interruptible) },
	{ 0x56ca8e02, __VMLINUX_SYMBOL_STR(register_framebuffer) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x2561b869, __VMLINUX_SYMBOL_STR(drm_panel_attach) },
	{ 0x84b183ae, __VMLINUX_SYMBOL_STR(strncmp) },
	{ 0xfbaaf01e, __VMLINUX_SYMBOL_STR(console_lock) },
	{ 0x73e20c1c, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xfd16e532, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xb2f3b8de, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0xa62d5e38, __VMLINUX_SYMBOL_STR(platform_device_unregister) },
	{ 0x7505bdef, __VMLINUX_SYMBOL_STR(memchr_inv) },
	{ 0x8e865d3c, __VMLINUX_SYMBOL_STR(arm_delay_ops) },
	{ 0x12da7344, __VMLINUX_SYMBOL_STR(drm_atomic_set_fb_for_plane) },
	{ 0xe836a4ae, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all_ctx) },
	{ 0xe5d8c966, __VMLINUX_SYMBOL_STR(devm_kfree) },
	{ 0x7c24d500, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0x2196324, __VMLINUX_SYMBOL_STR(__aeabi_idiv) },
	{ 0xfe487975, __VMLINUX_SYMBOL_STR(init_wait_entry) },
	{ 0x11dacec2, __VMLINUX_SYMBOL_STR(drm_property_replace_blob) },
	{ 0xf292a7e6, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0x6054d4, __VMLINUX_SYMBOL_STR(drm_modeset_unlock) },
	{ 0xe468260d, __VMLINUX_SYMBOL_STR(drm_modeset_lock) },
	{ 0x20645642, __VMLINUX_SYMBOL_STR(drm_debug) },
	{ 0xe18f0425, __VMLINUX_SYMBOL_STR(drm_mode_validate_size) },
	{ 0xcba8ac61, __VMLINUX_SYMBOL_STR(drm_crtc_wait_one_vblank) },
	{ 0x815c96d0, __VMLINUX_SYMBOL_STR(drm_mode_connector_list_update) },
	{ 0x2ae0285d, __VMLINUX_SYMBOL_STR(drm_atomic_get_crtc_state) },
	{ 0x98b71c6, __VMLINUX_SYMBOL_STR(fb_dealloc_cmap) },
	{ 0x4059792f, __VMLINUX_SYMBOL_STR(print_hex_dump) },
	{ 0x2996a1fb, __VMLINUX_SYMBOL_STR(i2c_del_adapter) },
	{ 0x7e388d0b, __VMLINUX_SYMBOL_STR(drm_dev_printk) },
	{ 0x57bde66a, __VMLINUX_SYMBOL_STR(drm_framebuffer_remove) },
	{ 0x12e65c89, __VMLINUX_SYMBOL_STR(drm_mode_set_crtcinfo) },
	{ 0x4969d922, __VMLINUX_SYMBOL_STR(drm_plane_cleanup) },
	{ 0xf3207539, __VMLINUX_SYMBOL_STR(drm_printk) },
	{ 0xb1c3a01a, __VMLINUX_SYMBOL_STR(oops_in_progress) },
	{ 0xb995cc87, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0x5e7ec10b, __VMLINUX_SYMBOL_STR(drm_mode_prune_invalid) },
	{ 0xaba33e13, __VMLINUX_SYMBOL_STR(drm_atomic_set_crtc_for_plane) },
	{ 0xd9ce8f0c, __VMLINUX_SYMBOL_STR(strnlen) },
	{ 0x7ea08ef0, __VMLINUX_SYMBOL_STR(drm_connector_list_iter_end) },
	{ 0x12a38747, __VMLINUX_SYMBOL_STR(usleep_range) },
	{ 0xc436e23a, __VMLINUX_SYMBOL_STR(sys_fillrect) },
	{ 0x27da232f, __VMLINUX_SYMBOL_STR(drm_atomic_private_obj_fini) },
	{ 0x40d04664, __VMLINUX_SYMBOL_STR(console_trylock) },
	{ 0x58d2273e, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0x8ddd8aad, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0xba8bb333, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0xbec394ae, __VMLINUX_SYMBOL_STR(sys_imageblit) },
	{ 0x3507a132, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0xb053adda, __VMLINUX_SYMBOL_STR(drm_rect_rotate) },
	{ 0x1271c18d, __VMLINUX_SYMBOL_STR(drm_sysfs_hotplug_event) },
	{ 0x8af1e6fe, __VMLINUX_SYMBOL_STR(fb_sys_write) },
	{ 0x1b3a8711, __VMLINUX_SYMBOL_STR(drm_mode_debug_printmodeline) },
	{ 0x78e7fd13, __VMLINUX_SYMBOL_STR(wait_for_completion_interruptible_timeout) },
	{ 0x44564d0c, __VMLINUX_SYMBOL_STR(drm_bridge_mode_fixup) },
	{ 0xb2038652, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0xe4a92e70, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_get) },
	{ 0xf96639f8, __VMLINUX_SYMBOL_STR(drm_mode_object_put) },
	{ 0xff17440, __VMLINUX_SYMBOL_STR(drm_bridge_remove) },
	{ 0xbd0c139d, __VMLINUX_SYMBOL_STR(drm_add_modes_noedid) },
	{ 0xfa71bd60, __VMLINUX_SYMBOL_STR(dma_fence_wait_timeout) },
	{ 0xc3945e9e, __VMLINUX_SYMBOL_STR(devres_add) },
	{ 0x7a9f42fb, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x598542b2, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x9f039115, __VMLINUX_SYMBOL_STR(drm_warn_on_modeset_not_all_locked) },
	{ 0x5addffc4, __VMLINUX_SYMBOL_STR(drm_atomic_clean_old_fb) },
	{ 0x741dea1, __VMLINUX_SYMBOL_STR(drm_gem_cma_describe) },
	{ 0x9cd4a062, __VMLINUX_SYMBOL_STR(drm_modeset_acquire_init) },
	{ 0x4215a929, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x6f0d015d, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0x80f0dfbf, __VMLINUX_SYMBOL_STR(framebuffer_alloc) },
	{ 0x9e52ac12, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x41e33cca, __VMLINUX_SYMBOL_STR(fb_deferred_io_cleanup) },
	{ 0xc31b9f21, __VMLINUX_SYMBOL_STR(drm_mode_set_config_internal) },
	{ 0x95a2b927, __VMLINUX_SYMBOL_STR(fb_deferred_io_init) },
	{ 0x37c26acf, __VMLINUX_SYMBOL_STR(drm_connector_list_iter_begin) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0xbaa349e1, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0xa28078b2, __VMLINUX_SYMBOL_STR(drm_edid_duplicate) },
	{ 0xb9cad492, __VMLINUX_SYMBOL_STR(__drm_atomic_state_free) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x4702d955, __VMLINUX_SYMBOL_STR(drm_mode_object_get) },
	{ 0x6900d335, __VMLINUX_SYMBOL_STR(drm_rect_clip_scaled) },
	{ 0xef3c1cf0, __VMLINUX_SYMBOL_STR(drm_panel_detach) },
	{ 0x2256fafa, __VMLINUX_SYMBOL_STR(div64_u64_rem) },
	{ 0x5e5dc0df, __VMLINUX_SYMBOL_STR(drm_mode_equal) },
	{ 0x78b883e6, __VMLINUX_SYMBOL_STR(request_firmware) },
	{ 0xba02fdf6, __VMLINUX_SYMBOL_STR(drm_atomic_private_obj_init) },
	{ 0x4a28d9ce, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all) },
	{ 0x98dfb43, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x62a4e95b, __VMLINUX_SYMBOL_STR(dma_common_mmap) },
	{ 0x2cce1981, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_count) },
	{ 0x2d50570f, __VMLINUX_SYMBOL_STR(drm_rect_calc_hscale) },
	{ 0x33092fbf, __VMLINUX_SYMBOL_STR(cfb_copyarea) },
	{ 0xf5da186, __VMLINUX_SYMBOL_STR(drm_atomic_add_affected_connectors) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0xd7e0a7d9, __VMLINUX_SYMBOL_STR(drm_mode_probed_add) },
	{ 0xb2d48a2e, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x1f010653, __VMLINUX_SYMBOL_STR(drm_modeset_unlock_all) },
	{ 0x742674e6, __VMLINUX_SYMBOL_STR(drm_bridge_mode_set) },
	{ 0xa4512a0a, __VMLINUX_SYMBOL_STR(drm_atomic_get_private_obj_state) },
	{ 0xb84957d, __VMLINUX_SYMBOL_STR(drm_mode_plane_set_obj_prop) },
	{ 0x8e48b58c, __VMLINUX_SYMBOL_STR(drm_atomic_add_affected_planes) },
	{ 0x52c07df, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0x93d66c0e, __VMLINUX_SYMBOL_STR(drm_mode_connector_set_tile_property) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0x84a203c6, __VMLINUX_SYMBOL_STR(devm_kmalloc) },
	{ 0x29dec96f, __VMLINUX_SYMBOL_STR(wait_for_completion_timeout) },
	{ 0xcbc9557f, __VMLINUX_SYMBOL_STR(unregister_sysrq_key) },
	{ 0x3ac1fef9, __VMLINUX_SYMBOL_STR(drm_mode_legacy_fb_format) },
	{ 0x1e159720, __VMLINUX_SYMBOL_STR(drm_bridge_add) },
	{ 0xbabec74e, __VMLINUX_SYMBOL_STR(drm_mode_object_find) },
	{ 0x58fbab7a, __VMLINUX_SYMBOL_STR(release_firmware) },
	{ 0xb859f38b, __VMLINUX_SYMBOL_STR(krealloc) },
	{ 0x71316482, __VMLINUX_SYMBOL_STR(drm_mode_vrefresh) },
	{ 0xa4097127, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
	{ 0xb8c0599a, __VMLINUX_SYMBOL_STR(unregister_framebuffer) },
	{ 0xefcc8ee9, __VMLINUX_SYMBOL_STR(drm_crtc_add_crc_entry) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,fb_sys_fops,syscopyarea,sysfillrect,sysimgblt";


MODULE_INFO(srcversion, "9F1994F2A0E8E16B57B8D0C");
