#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);
MODULE_INFO(name, KBUILD_MODNAME);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

#ifdef RETPOLINE
MODULE_INFO(retpoline, "Y");
#endif

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x367398b6, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xa7d53eae, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x7f9f07e3, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xf3e8cd8d, __VMLINUX_SYMBOL_STR(sb_min_blocksize) },
	{ 0xff178f6, __VMLINUX_SYMBOL_STR(__aeabi_idivmod) },
	{ 0x665007e4, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0xf3e8c2c1, __VMLINUX_SYMBOL_STR(unload_nls) },
	{ 0x30daf287, __VMLINUX_SYMBOL_STR(make_bad_inode) },
	{ 0x4d3e8d78, __VMLINUX_SYMBOL_STR(generic_file_llseek) },
	{ 0x4e360a13, __VMLINUX_SYMBOL_STR(__mark_inode_dirty) },
	{ 0xb4c6db64, __VMLINUX_SYMBOL_STR(mem_map) },
	{ 0x7f632d9d, __VMLINUX_SYMBOL_STR(__set_page_dirty_nobuffers) },
	{ 0xd6ee688f, __VMLINUX_SYMBOL_STR(vmalloc) },
	{ 0x349cba85, __VMLINUX_SYMBOL_STR(strchr) },
	{ 0x7aa1756e, __VMLINUX_SYMBOL_STR(kvfree) },
	{ 0xdc0b4130, __VMLINUX_SYMBOL_STR(generic_write_checks) },
	{ 0x6aecb77b, __VMLINUX_SYMBOL_STR(clean_bdev_aliases) },
	{ 0x188a3dfb, __VMLINUX_SYMBOL_STR(timespec_trunc) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0x97ec1ff, __VMLINUX_SYMBOL_STR(_raw_write_lock_irqsave) },
	{ 0x4b9abd92, __VMLINUX_SYMBOL_STR(iget5_locked) },
	{ 0x45379ad0, __VMLINUX_SYMBOL_STR(from_kuid_munged) },
	{ 0xe3e40e2a, __VMLINUX_SYMBOL_STR(end_buffer_write_sync) },
	{ 0x2494fd3c, __VMLINUX_SYMBOL_STR(block_invalidatepage) },
	{ 0x98e13541, __VMLINUX_SYMBOL_STR(generic_fh_to_parent) },
	{ 0xafc672ba, __VMLINUX_SYMBOL_STR(block_is_partially_uptodate) },
	{ 0x7c5fab68, __VMLINUX_SYMBOL_STR(is_bad_inode) },
	{ 0x56414597, __VMLINUX_SYMBOL_STR(pagecache_get_page) },
	{ 0x1c8d07f9, __VMLINUX_SYMBOL_STR(generic_file_open) },
	{ 0xde7ee60a, __VMLINUX_SYMBOL_STR(__lock_page) },
	{ 0xcb887a7b, __VMLINUX_SYMBOL_STR(__lock_buffer) },
	{ 0x20000329, __VMLINUX_SYMBOL_STR(simple_strtoul) },
	{ 0x2a3aa678, __VMLINUX_SYMBOL_STR(_test_and_clear_bit) },
	{ 0x45b4c1f6, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x435fe470, __VMLINUX_SYMBOL_STR(buffer_migrate_page) },
	{ 0x987c11c7, __VMLINUX_SYMBOL_STR(__pv_phys_pfn_offset) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0xa486600d, __VMLINUX_SYMBOL_STR(init_user_ns) },
	{ 0xecaacc86, __VMLINUX_SYMBOL_STR(add_to_page_cache_lru) },
	{ 0xe4ca3b4f, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x49ffa62f, __VMLINUX_SYMBOL_STR(mount_bdev) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0xcdf9b41d, __VMLINUX_SYMBOL_STR(d_add) },
	{ 0xe66dfa03, __VMLINUX_SYMBOL_STR(generic_read_dir) },
	{ 0x999e8297, __VMLINUX_SYMBOL_STR(vfree) },
	{ 0x84719ff, __VMLINUX_SYMBOL_STR(__getblk_gfp) },
	{ 0x91c382f9, __VMLINUX_SYMBOL_STR(igrab) },
	{ 0x47fdf373, __VMLINUX_SYMBOL_STR(unlock_buffer) },
	{ 0x423bfe7b, __VMLINUX_SYMBOL_STR(redirty_page_for_writepage) },
	{ 0xd697e69a, __VMLINUX_SYMBOL_STR(trace_hardirqs_on) },
	{ 0xb6d6b3dd, __VMLINUX_SYMBOL_STR(__alloc_pages_nodemask) },
	{ 0x903803ba, __VMLINUX_SYMBOL_STR(set_page_dirty) },
	{ 0x4091356e, __VMLINUX_SYMBOL_STR(truncate_setsize) },
	{ 0xa8401839, __VMLINUX_SYMBOL_STR(iov_iter_fault_in_readable) },
	{ 0x7f23a6b3, __VMLINUX_SYMBOL_STR(mutex_trylock) },
	{ 0xe5bd22c1, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0xceed7f85, __VMLINUX_SYMBOL_STR(_raw_write_unlock_irqrestore) },
	{ 0x619067c, __VMLINUX_SYMBOL_STR(end_page_writeback) },
	{ 0x7fb8d8c6, __VMLINUX_SYMBOL_STR(from_kgid_munged) },
	{ 0xde9360ba, __VMLINUX_SYMBOL_STR(totalram_pages) },
	{ 0xccf86c85, __VMLINUX_SYMBOL_STR(make_kgid) },
	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
	{ 0x77da0843, __VMLINUX_SYMBOL_STR(__insert_inode_hash) },
	{ 0x7a2add7d, __VMLINUX_SYMBOL_STR(current_kernel_time64) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xfeb3b960, __VMLINUX_SYMBOL_STR(d_add_ci) },
	{ 0xa0b399e, __VMLINUX_SYMBOL_STR(__bread_gfp) },
	{ 0x2aee63f4, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x6e2eb19f, __VMLINUX_SYMBOL_STR(d_obtain_alias) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xdfe19739, __VMLINUX_SYMBOL_STR(write_inode_now) },
	{ 0x741b6f29, __VMLINUX_SYMBOL_STR(file_remove_privs) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x3b216107, __VMLINUX_SYMBOL_STR(ilookup5_nowait) },
	{ 0xb9d9698d, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x93a6e0b2, __VMLINUX_SYMBOL_STR(io_schedule) },
	{ 0xfd16e532, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x23be5a8f, __VMLINUX_SYMBOL_STR(set_nlink) },
	{ 0xe2dee591, __VMLINUX_SYMBOL_STR(__wait_on_buffer) },
	{ 0x4175fba4, __VMLINUX_SYMBOL_STR(file_update_time) },
	{ 0x2489dd62, __VMLINUX_SYMBOL_STR(sync_dirty_buffer) },
	{ 0x7018048, __VMLINUX_SYMBOL_STR(unlock_page) },
	{ 0xa3a68caa, __VMLINUX_SYMBOL_STR(generic_file_read_iter) },
	{ 0xbc576ce5, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0xf7d05587, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0x90f424fb, __VMLINUX_SYMBOL_STR(__brelse) },
	{ 0x967aa69b, __VMLINUX_SYMBOL_STR(balance_dirty_pages_ratelimited) },
	{ 0xace7bf68, __VMLINUX_SYMBOL_STR(ilookup5) },
	{ 0xfe558bb2, __VMLINUX_SYMBOL_STR(mark_buffer_async_write) },
	{ 0xd62be11f, __VMLINUX_SYMBOL_STR(file_write_and_wait_range) },
	{ 0x153797e4, __VMLINUX_SYMBOL_STR(inode_init_once) },
	{ 0x5ab2b814, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xe1f0ab3a, __VMLINUX_SYMBOL_STR(_raw_read_lock_irqsave) },
	{ 0xa09d8501, __VMLINUX_SYMBOL_STR(generic_file_mmap) },
	{ 0xdc8a6d49, __VMLINUX_SYMBOL_STR(free_buffer_head) },
	{ 0x423a743, __VMLINUX_SYMBOL_STR(sync_blockdev) },
	{ 0x664ace8e, __VMLINUX_SYMBOL_STR(truncate_inode_pages_final) },
	{ 0xc81787c0, __VMLINUX_SYMBOL_STR(create_empty_buffers) },
	{ 0x54b69749, __VMLINUX_SYMBOL_STR(make_kuid) },
	{ 0xaa6f383, __VMLINUX_SYMBOL_STR(load_nls) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x5095f50a, __VMLINUX_SYMBOL_STR(unlock_new_inode) },
	{ 0x27b3803c, __VMLINUX_SYMBOL_STR(kill_block_super) },
	{ 0x9cba3c37, __VMLINUX_SYMBOL_STR(_raw_read_unlock_irqrestore) },
	{ 0x800fb92b, __VMLINUX_SYMBOL_STR(full_name_hash) },
	{ 0x733accc6, __VMLINUX_SYMBOL_STR(submit_bh) },
	{ 0x7a9f42fb, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x7a4a8063, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x4ee89ba3, __VMLINUX_SYMBOL_STR(register_filesystem) },
	{ 0x88a4c422, __VMLINUX_SYMBOL_STR(__test_set_page_writeback) },
	{ 0xfcccd38b, __VMLINUX_SYMBOL_STR(I_BDEV) },
	{ 0x7d2ff4e1, __VMLINUX_SYMBOL_STR(blockdev_superblock) },
	{ 0x555259ef, __VMLINUX_SYMBOL_STR(iput) },
	{ 0x28d6861d, __VMLINUX_SYMBOL_STR(__vmalloc) },
	{ 0xfb8aabd1, __VMLINUX_SYMBOL_STR(read_cache_page) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x9b74aba3, __VMLINUX_SYMBOL_STR(inode_dio_wait) },
	{ 0x8406ac5b, __VMLINUX_SYMBOL_STR(ihold) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x643e0ce5, __VMLINUX_SYMBOL_STR(call_rcu_sched) },
	{ 0x2645ae64, __VMLINUX_SYMBOL_STR(current_time) },
	{ 0x49bbe1ae, __VMLINUX_SYMBOL_STR(load_nls_default) },
	{ 0x3c027438, __VMLINUX_SYMBOL_STR(generic_error_remove_page) },
	{ 0xde9b1b51, __VMLINUX_SYMBOL_STR(d_splice_alias) },
	{ 0x6a66666f, __VMLINUX_SYMBOL_STR(end_buffer_read_sync) },
	{ 0x6128b5fc, __VMLINUX_SYMBOL_STR(__printk_ratelimit) },
	{ 0x45e9de2a, __VMLINUX_SYMBOL_STR(sync_filesystem) },
	{ 0xb458979b, __VMLINUX_SYMBOL_STR(__set_page_dirty_buffers) },
	{ 0x30154f2d, __VMLINUX_SYMBOL_STR(sb_set_blocksize) },
	{ 0x7014f751, __VMLINUX_SYMBOL_STR(d_make_root) },
	{ 0x1db7dc40, __VMLINUX_SYMBOL_STR(pgprot_kernel) },
	{ 0x9b8cf3f8, __VMLINUX_SYMBOL_STR(iov_iter_advance) },
	{ 0x8b8d8ed2, __VMLINUX_SYMBOL_STR(iov_iter_copy_from_user_atomic) },
	{ 0x63c4d61f, __VMLINUX_SYMBOL_STR(__bitmap_weight) },
	{ 0x3264741d, __VMLINUX_SYMBOL_STR(iov_iter_single_seg_count) },
	{ 0x7f1fff66, __VMLINUX_SYMBOL_STR(mark_buffer_dirty) },
	{ 0xe640a603, __VMLINUX_SYMBOL_STR(unregister_filesystem) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0x93d3d503, __VMLINUX_SYMBOL_STR(new_inode) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0x99bb8806, __VMLINUX_SYMBOL_STR(memmove) },
	{ 0xd8b514d6, __VMLINUX_SYMBOL_STR(generic_file_splice_read) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0x38874d78, __VMLINUX_SYMBOL_STR(generic_fh_to_dentry) },
	{ 0xec3d2e1b, __VMLINUX_SYMBOL_STR(trace_hardirqs_off) },
	{ 0xe4946391, __VMLINUX_SYMBOL_STR(clear_inode) },
	{ 0x2b9bae74, __VMLINUX_SYMBOL_STR(__init_rwsem) },
	{ 0x1f9c8e0e, __VMLINUX_SYMBOL_STR(flush_dcache_page) },
	{ 0x93d216b1, __VMLINUX_SYMBOL_STR(alloc_page_buffers) },
	{ 0x65acf8bd, __VMLINUX_SYMBOL_STR(__put_page) },
	{ 0x2baae298, __VMLINUX_SYMBOL_STR(vfs_fsync_range) },
	{ 0x494165be, __VMLINUX_SYMBOL_STR(setattr_prepare) },
	{ 0x3d7e92b8, __VMLINUX_SYMBOL_STR(noop_backing_dev_info) },
	{ 0xce4695bc, __VMLINUX_SYMBOL_STR(truncate_inode_pages) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";


MODULE_INFO(srcversion, "F45E2E070FE0A8726717A11");
